dist: trusty 
language: cpp
sudo: required

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

  sonarqube:
    organization: "fabi1816-github"

script:
  - mkdir build
  - cd build
  - cmake ../src
  # Wrap the compiled app in sonar qube 
  - build-wrapper-linux-x86-64 --out-dir bw-output make
  - cd ..
  - sonar-scanner
  
cache:
  directories:
    - '$HOME/.sonar/cache'
